<?php

return [
    //Super Admin
    'Super Admin' => [
        'dashboard' => 1,
        'units_management' =>1,
        'units_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,            
            'change_status' => 1,
        ], 
        'categories_management' =>1,
        'categories_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,            
            'change_status' => 1,
        ], 
        'sub_categories_management' =>1,
        'sub_categories_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,            
            'change_status' => 1,
        ], 
        'product_details_management' =>1,
        'product_details_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,            
            'change_status' => 1,
        ], 
        'labour_categories_management' => 1,
        'labour_categories_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,
            'change_password' => 1,
            'delete' => 1,
            'change_status' => 1,
        ],
        'property_categories_management' => 1,
        'property_categories_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,
            'change_password' => 1,
            'delete' => 1,
            'change_status' => 1,
        ],
        'ownership_management' => 1,
        'ownership_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,
            'change_password' => 1,
            'delete' => 1,
            'change_status' => 1,
        ],
        'property_name_management' => 1,
        'property_name_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,
            'change_password' => 1,
            'delete' => 1,
            'change_status' => 1,
        ],
        'centering_materials_management' => 1,
        'centering_materials_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,
            'change_password' => 1,
            'delete' => 1,
            'change_status' => 1,
        ],
        'lorry_materials_management' => 1,
        'lorry_materials_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,
            'change_password' => 1,
            'delete' => 1,
            'change_status' => 1,
        ],
        'shop_materials_management' => 1,
        'shop_materials_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,
            'change_password' => 1,
            'delete' => 1,
            'change_status' => 1,
        ],
        'toolsplants_materials_management' => 1,
        'toolsplants_materials_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,
            'change_password' => 1,
            'delete' => 1,
            'change_status' => 1,
        ],
        'vehicle_materials_management' => 1,
        'vehicle_materials_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,
            'change_password' => 1,
            'delete' => 1,
            'change_status' => 1,
        ],

        'architect_site_management' => 1,
        'architect_site_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,
            'change_password' => 1,
            'delete' => 1,
            'change_status' => 1,
        ],
        'client_site_management' => 1,
        'client_site_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,
            'change_password' => 1,
            'delete' => 1,
            'change_status' => 1,
        ],
        'user_management' => 1,
        'user_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,
            'change_password' => 1,
            'delete' => 1,
            'change_status' => 1,
        ],
        'customer_management' => 1,
        'customer_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,
            'delete' => 1,
            'change_status' => 1,
        ],
        'stock_management' => 1,
        'stock_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,
            'delete' => 1,
            'change_status' => 1,
        ],
        'roles_management' =>1,
        'roles_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,            
            'change_status' => 1,
        ],
        'clients_management' =>1,
        'clients_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,            
            'change_status' => 1,
        ],
        'change_profile_password' => 1,
        'staffgroups_management' =>1,
        'staffgroups_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,            
            'change_status' => 1,
        ],
        'staff_details_management' =>1,
        'staff_details_management_access' => [
            'create' => 1,
            'edit' => 1,
            'view' => 1,            
            'change_status' => 1,
        ],
    ],
];
